#!/bin/bash
# Usage: scripts/pretest
# Starts the project's prettest.


# stops script on errors
set -e errexit

bash ./scripts/build
node ./scripts/lib/server.js --port=3000 --verbose --root ./dist > /dev/null &
webdriver-manager update

