#!/bin/bash
# Usage: script/start
# Starts the project's development server.
# not used in Nitrous Build

# stops script on errors
set -e errexit

cp -R ./src/**/*.html ./dist
node ./scripts/lib/server.js --port=3000 --verbose --root ./dist > /dev/null &
protractor
